dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0          # Cliente HTTP
  provider: ^6.1.1     # Gerenciamento de estado
  intl: ^0.19.0        # Formatação de datas
  image_picker: ^1.0.5  # Seleção de imagens (para upload)
  flutter_local_notifications: ^16.1.0  # Notificações locais
  path_provider: ^2.1.1 # Para salvar arquivos localmente